version: "3.9"
services:
  scrapy:
    build: scrapy
    depends_on:
      - "news-queue"
    networks:
      - queue
  news-queue:
    image: rabbitmq:3-management
    restart: on-failure
    networks:
      - queue
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
  deduplicator:
    build: deduplicator
    networks:
      - queue
    depends_on:
      - "news-queue"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  answerer:
    build: answerer
    networks:
      - queue
    depends_on:
      - "news-queue"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  import:
    build: import
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-queue"
      - "news-database"
    restart: on-failure
    networks:
      - queue
      - database
  summarizer:
    build: summarizer
    depends_on:
      - "news-queue"
    restart: on-failure
    networks:
      - queue
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  news-database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
    networks:
      - database
  restapi:
    build: restapi
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-database"
    networks:
      - database
      - web
  front:
    build: front
    depends_on:
      - "restapi"
    ports:
      - "8001:80"
    networks:
      - web
  opus-mt:
    build: Opus-MT
    image: opus-mt-base
    profiles:
      - donotstart
  translator:
    build: translator

secrets:
  postgres-password:
    file: ./postgres-password

networks:
  database:
  queue:
  web:
