version: "3.9"
services:
  scrapy:
    build: scrapy
    depends_on:
      - "scrapy-queue"
  scrapy-queue:
    image: rabbitmq:3-management
#  import:
#    build: import
#    volumes:
#      - ./database:/database
#  restapi:
#    build: restapi
#    volumes:
#      - ./database:/database
#  front:
#    build: front
