version: "3.9"
services:
  scrapy:
    build: scrapy
    depends_on:
      - "news-queue"
  news-queue:
    image: rabbitmq:3-management
    restart: on-failure
  import:
    build: import
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-queue"
      - "news-database"
    restart: on-failure
  summarizer:
    build: summarizer
    depends_on:
      - "news-queue"
    restart: on-failure
  news-database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
  restapi:
    build: restapi
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-database"
  front:
    build: front
    depends_on:
      - "restapi"

secrets:
  postgres-password:
    file: ./postgres-password
