version: "3.9"
services:
  scrapy:
    build: scrapy
    depends_on:
      - "news-queue"
    networks:
      - queue:
        alias: scrapy
  news-queue:
    image: rabbitmq:3-management
    restart: on-failure
    networks:
      - queue:
        alias: news-queue
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
  deduplicator:
    build:
      context: ./deduplicator
      target: deduplicator
    networks:
      - queue:
        alias: deduplicator
    depends_on:
      - "news-queue"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  deduplicator_test:
    build: deduplicator
    image: deduplicator_test
    depends_on:
      - "news-queue"
      - "translator"
    restart: "no"
    networks:
      - queue:
        alias: deduplicator_test
    profiles:
      - donotstart
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  import:
    build: import
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-queue"
      - "news-database"
    restart: on-failure
    networks:
      - queue:
        alias: import_on_queue
      - database:
        alias: import_on_database
  summarizer:
    build:
      context: ./summarizer
      target: summarizer
    image: summarizer
    depends_on:
      - "news-queue"
      - "translator"
    restart: on-failure
    networks:
      - queue:
        alias: summarizer_on_queue
      - translator-summarizer:
        alias: summarizer_on_translator_summarizer
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  summarizer_test:
    build: summarizer
    image: summarizer_test
    depends_on:
      - "news-queue"
      - "translator"
    restart: "no"
    networks:
      - queue:
        alias: summarizer_test_on_queue
      - translator-summarizer:
        alias: summarizer_on_translator_summarizer
    profiles:
      - donotstart
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  news-database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
    networks:
      - database:
        alias: news_database
    volumes:
      - pgdata:/var/lib/postgresql/data
  restapi:
    build: restapi
    env_file: ./postgres-config
    secrets:
      - postgres-password
    depends_on:
      - "news-database"
    networks:
      - database:
        alias: restapi_on_database
      - web:
        alias: restapi_on_web
  front:
    build: front
    depends_on:
      - "restapi"
    ports:
      - "8001:80"
    networks:
      - web:
        alias: front
  opus-mt:
    build: Opus-MT
    image: opus-mt-base
    profiles:
      - donotstart
  translator:
    build: translator
    networks:
      - translator-summarizer:
        alias: translator
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

secrets:
  postgres-password:
    file: ./postgres-password

networks:
  database:
  queue:
  web:
  translator-summarizer:

volumes:
  pgdata:
  rabbitmqdata:
