version: "3.9"
services:
  scrapy:
    build: scrapy
    depends_on:
      - "scrapy-queue"
  scrapy-queue:
    image: rabbitmq:3-management
  import:
    build: import
    env_file: ./postgres-config
    secrets:
      - postgres-password
  news-database:
    image: postgres
    env_file: ./postgres-config
    secrets:
      - postgres-password
  restapi:
    build: restapi
    env_file: ./postgres-config
    secrets:
      - postgres-password
#  front:
#    build: front
#
secrets:
  postgres-password:
    file: ./postgres-password
